### ISSUE TITLE
Removing PHPUnit?

### ISSUE THREAD

**Issue by ryanxada** [ryanxada/aero#9]
I know PHPUnit is widely used but I'm second guessing the decision to include it as part of the core framework. My concerns are:

1. The learning curve is too steep for developers interested in embracing a low-level framework like aero. I know you don't have to use it, and it's just as important for the framework authors, but I think on some level it could turn off possible early adopters.

2. Tying it to a specific framework is too strict. I'm partial to Codeception, which is based on PHPUnit, but I think that choice should be left up to the individual developer.

The initial decision to include might haven't been thought all the way through, and that's my fault. @karllhughes I' be interested to hear your thought here.

**Comment by karllhughes** [comment]
Good points. My thoughts:

1. I agree that it shouldn't be mandatory for projects, and you're right we don't want to turn people off just because they see it there. Maybe documentation around how unit testing works and the fact that it's completely optional could mitigate this problem?

2. PHPUnit is the unquestionable standard in PHP. [Codeception has it as a dependency](https://github.com/Codeception/Codeception/blob/2.1/composer.json#L21), and most of our projects dependencies also rely on it ([see Klein's composer file](https://github.com/chriso/klein.php/blob/master/composer.json#L25)) anyway. Since it only actually gets built in dev it doesn't really add overhead either.

The biggest reason I would advocate not removing it is that in an open source project like this it's highly important that developers who work on the core project be on the same page with standards and testing. If we have more contributors, it is impossible to trust the work they make without some kind of testing, and I personally don't want to have to do all of it manually.

Some options:

- We could bundle and release the core classes as their own composer package (right now it's just the Boot class, but maybe we add more), and then include them in the composer package of the main aero project. That way, the core classes can be tested without including PHPUnit in the main project.
- We could beef up documentation and examples (I'm happy to help with this) to show new users how PHPUnit works and that it's optional, but nice for complex projects.

I think it's good to question things, but we have to have some way of testing the core parts of our project if we want to keep it stable over time.

**Comment by ryanxada** [comment]
I thought about this some more today and after reading your response I thought I'd bat it back one more time before closing the issue. In thinking about the scope of the project, the goal is definitely to have more people *use* the framework than *contribute* to the framework (keepin' it slim), so early adoption by casual developers is the main goal and any barrier to entry that can be lowered, should be. I feel like the folks willing to contribute will already be familiar enough with unit testing to have a preferred framework of their own and should make that decision independently. 

That said, I know how important testing is to keeping the core stable and any barrier we can lower to that end should be considered as well. What seemed like an easy decision to include PHPUnit is now more of a philosophical one instead of a practical one, at least for me. Do my ridiculous amateur ramblings have any legs? Is it practical to create a separate testing suite to be used just in conjunction with aero and keep the main testing files out of core? It would mean necessarily updating both repos every time a class was added. This is an interesting issue (to me anyway).

**Comment by ryanxada** [comment]
Keeping it is the right decision. In the interest of simplicity and ease of maintenance, I like your suggestion about improving the documentation. Could be a good time to start a wiki. How would you propose handling the documentation? Beefing up the README or some other way?

**Comment by karllhughes** [comment]
I think we could start by just including things in the Readme. Eventually we could make a [Github pages branch](https://help.github.com/articles/creating-project-pages-manually/) on the repo to store more detailed docs and examples. I'll make another issue and start some work on it next week.
